apiVersion: v1
data:
  mapRoles: 
    - groups:
      - system: masters
      - system:nodes
      rolearn: arn:aws:iam::670689504078:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::670689504078:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HXM1ODL04Q1K
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-14T16:34:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1617"
  uid: c43299d9-0ad5-44b5-a922-9764543201a7
